#!/usr/bin/env bash
#MISE description="generate completions"
#MISE hide=true
#MISE sources=["**/*.go"]
#MISE outputs=["completions/lech-linter.*"]
set -euo pipefail

rm -rf completions
mkdir completions

for sh in bash zsh fish; do
	go run . completion "$sh" >"completions/lech-linter.$sh"
done
